name: auth_example
description: Demonstrates how to use the auth Flutter package.
publish_to: 'none' # Prevent accidental publishing of the example app

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  auth: # Depends on the auth package
    path: ../ # Path to the auth package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
