name: shopeein
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  bloc: ^8.0.0
  dio: ^4.0.6
  http: ^0.13.4
  get_it: ^7.2.0
  google_fonts: ^2.3.2
  shared_preferences: ^2.0.6
  nb_utils: ^4.4.1
  carousel_slider: ^4.1.1
  flutter_native_splash: ^2.2.4
  cached_network_image: ^3.2.1
  iconly: ^1.0.1
  flutter_feather_icons: ^2.0.0+1
  percent_indicator: ^4.2.2
  modal_bottom_sheet: ^2.0.1
  flutter_slidable: ^1.3.0
  flutter_credit_card: ^3.0.1
  animated_splash_screen: ^1.3.0
  timeline_tile: ^2.0.0
  syncfusion_flutter_sliders: ^20.1.56
  string_validator: ^0.3.0
  flutter_sticky_header: ^0.6.4
  device_info_plus: ^3.2.3
  fluttertoast: ^8.1.1
  group_radio_button: ^1.2.0
  pin_code_fields: ^7.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/Launching_Icon_App.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter:
  uses-material-design: true
  assets:
    - assets/icons/Launching_Icon_App.png
    - assets/images/
    - assets/icons/
    - images/
  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf
        - asset: assets/fonts/Product-Sans-Italic.ttf
          style: italic
        - asset: assets/fonts/Product-Sans-Bold.ttf
          weight: 700



