name: network_core
description: A standalone Dart package for handling networking, including HTTP client, error handling, and configuration.
version: 0.0.1
# repository: https://github.com/your_org/network_core # Example
# homepage: https://example.com/network_core # Example

environment:
  sdk: '>=2.19.0 <4.0.0' # Current Dart 3.0.0 uses >=3.0.0 <4.0.0. This range is fine.

dependencies:
  dio: ^5.3.3
  logging: ^1.2.0

dev_dependencies:
  lints: ^2.1.0
  mocktail: ^1.0.0
  test: ^1.24.3

# No Flutter section as it's a Dart-only package
