name: auth
description: A reusable Flutter login package following clean architecture.
version: 0.0.1
# homepage: https://example.com/auth
# repository: https://github.com/your_org/auth_package

environment:
  sdk: '>=2.19.0 <4.0.0' # Adjusted to a common recent range
  flutter: ">=1.17.0"    # Standard Flutter constraint

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6 # Updated to a more recent version
  flutter_riverpod: ^2.4.0 # Updated to a more recent version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Added flutter_lints
  mocktail: ^1.0.0 # Added mocktail for testing

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
# (No specific Flutter assets or fonts defined for this package yet)
